version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27018"
    volumes:
      - mongodb_data:/data/db

  microservice-2:
    build:
      context: /Users/tamaraj/Documents/SIPIA 1.2/ITA/Vaje/Vaja 2
    container_name: microservice-2
    ports:
      - "8080:8080"
    depends_on:
      - mongodb

volumes:
  mongodb_data:
